version: '2'
services:
    rabbit:
        image: rabbitmq:3-management
        environment:
            - RABBITMQ_DEFAULT_USER=z43
            - RABBITMQ_DEFAULT_PASS=z43
        ports:
            - "15672:15672"
        depends_on:
            - db
    flower:
        image: ondrejit/flower:latest
        command: --broker=amqp://z43:z43@rabbit:5672
        ports:
            - 5555:5555
        depends_on:
            - db
            - app
    db:
        image: mysql:5.7
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=z43
            - MYSQL_DATABASE=dag_celery
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
        depends_on:
            - db
    app:
        build:
            context: .
            dockerfile: ./dag/Dockerfile
        volumes:
            - ./dag/dag/:/app/dag/
        depends_on:
            - rabbit
            - db
    dev:
        build:
            context: .
            dockerfile: ./dev/Dockerfile
        volumes:
            - ./dev/dag/:/app/dag/
        depends_on:
            - rabbit
            - db
    database:
        image: mongo:3.4.0
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/dev/null
        volumes:
            - db:/data/db
        ports:
            - "28017:28017"
        command: mongod --httpinterface --rest --smallfiles --logpath=/dev/null # --quiet
    database_ui:
        image: mongo-express
        ports:
            - "8081:8081"
        environment:
            - ME_CONFIG_MONGODB_SERVER=database
        depends_on:
            - database
volumes:
    db: