version: '3'
services:
  director:
    image: masu.speag.com/simcore/comp.backend/director:1.2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8010:8010"
    dns:
      - 172.16.8.15
    depends_on:
      - rabbit
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]
  sidecar:
    image: masu.speag.com/simcore/comp.backend/sidecar:1.2
    volumes:
      - input:/input
      - output:/output
      - log:/log
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:8000"
    dns:
      - 172.16.8.15
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]
  database:
    image: mongo:3.4.0
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - db:/data/db
    ports:
      - "28017:28017"
    command: mongod --httpinterface --rest --smallfiles --logpath=/dev/null # --quiet
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
  database_ui:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=database
    depends_on:
      - database
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
  rabbit:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=z43
      - RABBITMQ_DEFAULT_PASS=z43
    ports:
      - "15672:15672"
    deploy:
      placement:
        constraints: [node.role == manager]
  flower:
    image: ondrejit/flower:latest
    command: --broker=amqp://z43:z43@rabbit:5672
    ports:
      - 5555:5555
    depends_on:
      - director
    deploy:
      placement:
        constraints: [node.role == manager]
  redis:
    image: redis
    deploy:
      placement:
        constraints: [node.role == manager]
  redis-commander:
    image:   ficusio/redis-commander
    command: --redis-host redis
    ports:
      - "8082:8081"
    depends_on:
      - redis
    deploy:
      placement:
        constraints: [node.role == manager]
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=z43
      - MYSQL_DATABASE=dag_celery
    deploy:
      placement:
        constraints: [node.role == manager]
  adminer:
    image: adminer
    restart: always
    ports:
      - 8070:8080
    depends_on:
      - db
    deploy:
      placement:
        constraints: [node.role == manager]
  qxapp:
    image: masu.speag.com/simcore/webserver/dag:1.2
    ports:
      - '8071:9090'
    depends_on:
      - director
    deploy:
      placement:
        constraints: [node.role == manager]
volumes:
  input:
  output:
  log:
  db:

