FROM python:3

# Selects appropriate 'server-py-*/' folder
ARG serverdir

ENV SIMCORE_WEB_OUTDIR=/usr/src/app/client
ENV SIMCORE_WEB_HOSTNAME='0.0.0.0'
ENV SIMCORE_WEB_PORT=8080

WORKDIR /usr/src/app

VOLUME ${SIMCORE_WEB_OUTDIR}
VOLUME /usr/src/app

COPY $serverdir/requirements-dev.txt requirements.txt
RUN python --version \
    && pip3 install --no-cache-dir -r ./requirements.txt \
    && pip list --format=columns

EXPOSE $SIMCORE_WEB_PORT

ENTRYPOINT adev runserver --host localhost --port 8080 --app-factory create_app server.py