version: '3'
services:
  pyaio:
    build:
      context: .
      dockerfile: _dockerfiles/qxapp/python/Dockerfile
      args:
        serverdir: server-py-aiohttp
        web_outdir: /usr/src/app/client
    env_file: .env
    ports:
      - '9081:8080'
    environment:
      - DIRECTOR_HOST=http://172.16.9.89
      - DIRECTOR_PORT=8001
  director:
    build:
      context: .
      dockerfile: _dockerfiles/director/Dockerfile
    ports:
      - '8001:8001'
    environment:
    # on Windows follow http://www.computerperformance.co.uk/powershell/powershell_profile_ps1.htm
    # currently needs to set $Env:COMPOSE_CONVERT_WINDOWS_PATHS=1 in powershell to make this works
    # on a windows machine      
      - REGISTRY_URL=masu.speag.com
      - REGISTRY_AUTH=True
      - REGISTRY_USER=z43
      - REGISTRY_PW=z43
      - LOCAL_MODE=True
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'