# Pipelines Project Make File
# author: Sylvain Anderegg

demo:
	docker swarm init
	docker-compose up	

start: 
	docker swarm init
	docker-compose up	

stop: 
	docekr-compose down
	docker swarm leave -f