matrix:
  include:
    # Use containers instead of full VMs for faster startup.
    - sudo: false
      language: python
      python:
        - "3.6"
      services:
        - docker
      # configure and buid
      install:
        - pip3 install pylint
        - mkdir _bin
        - cd _bin
        - cmake ..
        - make -j4
        - cd ..
      before_script:
        - pylint --version
      # command to run tests
      script:
        - cd _bin && ctest --parallel 1 -V && cd ..

    - language: node_js
      node_js:
        - "6"
      install:
        - "npm install -g npm@latest"
        - "npm install --save-dev eslint"
        - "npm install --save-dev babel-eslint"
        - "npm install --save-dev eslint-config-google"
        - "npm install --save-dev eslint-config-qx"
        - "npm install --save-dev eslint-plugin-qx-rules"
      before_script:
        - eslint --version
      script:
        - npm run lintBoilerplate
