# Use containers instead of full VMs for faster startup.
sudo: false

language: python

addons:
  apt:
    packages:
    - pylint

services:
  - docker

# configure and buid
install:
  - mkdir _bin
  - cd _bin
  - cmake ..
  - make -j4
  - cd ..

# command to run tests
script:
  - cd _bin && ctest --parallel 1 -V && cd ..

