# Use containers instead of full VMs for faster startup.
sudo: false

language: python
python:
  - "3.6"

addons:
  apt:
    packages:
    - pylint
    - clang

# configure and buid
install:
  - export CC=/usr/bin/clang
  - export CXX=/usr/bin/clang++
  - mkdir _bin
  - cd _bin
  - cmake ..
  - make -j4
  - cd ..

# command to run tests
script:
  - cd _bin && ctest --parallel 1 -V && cd ..

