site_name: D1.1 Technology Review & Technical Specs.
pages:
  - Home: 'd1.1-techreview/index.md'
  - Objectives: 'd1.1-techreview/objectives.md'
  - Methodology: 'd1.1-techreview/methodology.md'
  - Results:
    - 'Overview': 'd1.1-techreview/results.md'
    - 'Front-end': 'd1.1-techreview/parts/client-side.md'
    - 'Web-server': 'd1.1-techreview/parts/server-side.md'
    - 'Communication models': 'd1.1-techreview/parts/communication.md'
    - 'Computational services': 'd1.1-techreview/parts/comp-services.md'
    - 'Demonstrations': 'd1.1-techreview/parts/demos.md'
  - Conclusions: 'd1.1-techreview/conclusion.md'
theme: readthedocs
