site_name: D1.1 Technical Specs. & Technology Evaluation
docs_dir: './docs/d1.1-report'
pages:
  - Introduction: 'index.md'
  - Requirements Gathering:
    - 'Methodology': 'reqs/methodology.md'
    - 'Results': 'reqs/results.md'
    - 'Conclusions': 'reqs/conclusions.md'
  - Technology Evaluation:
    - Methodology: 'tech/methodology.md'
    - Front-end: 'tech/parts/client-side.md'
    - Web-server: 'tech/parts/server-side.md'
    - Communication models: 'tech/parts/communication.md'
    - Computational services: 'tech/parts/comp-services.md'
    - Demonstrations: 'tech/parts/demos.md'
    - Conclusions: 'tech/conclusion.md'
  - Specficications:
    - 'High Level Specifications': 'specs/high-level.md'
    - 'Low Level Specifications': 'specs/low-level.md'
  - Conclusions: 'conclusions.md'
theme: readthedocs
