site_name: D1.1 Technical Specs. & Technology Evaluation

pages:
  - Introduction: 'd1.1-report/index.md'
  - Requirements Gathering:
    - 'Methodology': 'd1.1-report/reqs/methodology.md'
    - 'Results': 'd1.1-report/reqs/results.md'
    - 'Conclusions': 'd1.1-report/reqs/conclusions.md'
  - Technology Evaluation:
    - Methodology: 'd1.1-report/tech/methodology.md'
    - Front-end: 'd1.1-report/tech/parts/client-side.md'
    - Web-server: 'd1.1-report/tech/parts/server-side.md'
    - Communication models: 'd1.1-report/tech/parts/communication.md'
    - Computational services: 'd1.1-report/tech/parts/comp-services.md'
    - Demonstrations: 'd1.1-report/tech/parts/demos.md'
    - Conclusions: 'd1.1-report/tech/conclusion.md'
  - Specficications:
    - 'High Level Specifications': 'd1.1-report/specs/high-level.md'
    - 'Low Level Specifications': 'd1.1-report/specs/low-level.md'
  - Conclusions: 'd1.1-report/conclusions.md'

theme: readthedocs
