FROM continuumio/miniconda3
MAINTAINER Manuel Guidon <guidon@itis.ethz.ch>

RUN conda install flask plotly pymongo
RUN conda install -c conda-forge pika

RUN pip install docker

EXPOSE 8000

WORKDIR /work
ADD *.py /work

CMD ["python", "sidecar.py"]
