# TODO: would be convenient to have this dockerfile combined with Dockerfile-dev
FROM node:6.11.5

ENV NPM_CONFIG_LOGLEVEL warn

RUN npm install -g serve
CMD serve -s build
EXPOSE 6001

WORKDIR /home/node/app/

COPY package.json package.json
COPY yarn.lock yarn.lock
RUN npm install

COPY . .

# Build for production.
CMD ["npm", "run", "start"]
