// ActionType.js

export const RADIUS_CHANGED = 'RADIUS_CHANGED';
export const SELECTED_SERVICE_CHANGED = 'SELECTED_SERVICE_CHANGED';
export const COMPUTE_OUTPUT_DATA = 'COMPUTE_OUTPUT_DATA';
export const LAYOUT_STYLE_CHANGED = 'LAYOUT_STYLE_CHANGED';
