FROM continuumio/miniconda
MAINTAINER Manuel Guidon <guidon@itis.ethz.ch>

RUN conda install flask plotly pymongo
RUN conda install -c conda-forge celery
RUN pip install docker

EXPOSE 8010

WORKDIR /work
ADD *.py /work

CMD ["python", "director.py"]
