version: '2'
services:
  jsnode:
    build:
      context: .
      dockerfile: _dockerfiles/qxapp/node/Dockerfile
      args:
        web_app_port: 9090
        s4l_ip: "172.16.9.89"
        s4l_port_app: 9095
        s4l_port_mod: 9096
    ports:
      - '8080:9090'
  pyaio:
    build:
      context: .
      dockerfile: _dockerfiles/qxapp/python/Dockerfile
      args:
        serverdir: server-py-aiohttp
    env_file: .env
    ports:
      - '8081:8080'
  pyflk:
    build:
      context: .
      dockerfile: _dockerfiles/qxapp/python/Dockerfile
      args:
        serverdir: server-py-flask-eventlet
    env_file: .env
    ports:
      - '8082:8080'