version: '3'
services:
  build-qx:
    build:
      context: .
      dockerfile: _dockerfiles/build-qx/Dockerfile
    working_dir: /home/node/qxapp
    volumes:
      - './client-qx:/home/node/qxapp'
