version: '3'
services:
  build-qx:
    build:
      context: .
      dockerfile: _dockerfiles/build-qx/Dockerfile
    volumes:
      - './client-qx:/home/node/qxapp'
  nodeexpress:
    build:
      context: .
      dockerfile: _dockerfiles/build-npm/Dockerfile
      args:
          web_app_port: 9090
          s4l_ip: "172.16.9.89"
          s4l_port_app: 9095
          s4l_port_mod: 9096
    ports:
      - '8080:9090'
    volumes: 
      - './server-node-express:/home/node'
      - './client-qx/source-output:/home/node/source-output'
      - './services-rpc-api:/home/node/services-rpc-api'
    depends_on: 
      - build-qx