
# Demo should implement these commands ------------
demo:
	echo "this should launch the demo (detached if possible)"

stop:
	echo "this should stop the demo"
#---------------------------------------------
